name: CI - Client (React)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: ./package.json
      - name: Install
        run: npm ci || npm i
      - name: Test
        run: npm run test
      #- name: Build
      #  run: npm run build
